server:
  port: 8081
  servlet:
    context-path: /v2



app:
  imgPath: D:/img/
  info: this is dev
  author: zhong
  email: 111111111@qq.com
  swaggerTitle: 这是我们的第一个swagger在线文档
  swaggerContactName: 熊昭
  swaggerContactWebUrl: https://www.baidu.com
  swaggerContactEmail: 972031129@qq.com
  swaggerVersion: v1.0.0
  swaggerDescription: springboot 在线接口文档
  swaggerTermsOfServiceUrl: https://www.baidu.com


spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root
    timeout: 5000
  datasource:
    username: root
    password: root
    name: druidDataSource
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    druid:
      filters: stat,wall,slf4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20


logging:
  level:
    com.example.* : debug



mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.whcb.model
